apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-api
  name: sample-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-api
  strategy: {}
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
        - image: bhasevambit/k8s_cluster_monitoring_as_code_sample_api
          name: sample-api
